FROM node:20.17.0-alpine

WORKDIR /app

# Instalar OpenSSL para Prisma
RUN apk add --no-cache openssl

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

RUN npm run prisma:generate

CMD ["npm", "run", "dev"]